name: Build & Deploy (pygbag)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pygbag (builder)
        run: |
          python -m pip install --upgrade pip
          pip install pygbag

      - name: Build web bundle with pygbag
        working-directory: game
        run: |
          python -m pygbag .

      - name: Upload Pages artifact (game/build/web)
        uses: actions/upload-pages-artifact@v3
        with:
          path: game/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
