name: Build & Deploy (pygbag)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pygbag
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pygbag==0.9.2"

      # Workaround: ensure pygbag doesn't try to format with Black (it’s optional and causes the error)
      - name: Remove Black if present
        run: |
          python -m pip uninstall -y black || true

      # Optional: quiets an ffmpeg warning (not required, but nice)
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build web bundle with pygbag (from game/)
        working-directory: game
        run: |
          python -m pygbag .

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: game/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
