name: Build & Deploy (pygbag)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Optional but removes the two warnings
      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install pygbag (and black)
        run: |
          python -m pip install --upgrade pip
          pip install "pygbag>=0.9" black

      # Build the web bundle from your game folder
      - name: Build web bundle with pygbag
        working-directory: ./game
        run: |
          python -m pygbag .

      # Publish the /game/build/web directory
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: game/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
